# Generated by Django 4.2.4 on 2023-08-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0002_values_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='values',
            name='last_income',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
