# Generated by Django 4.2.4 on 2023-08-19 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0003_values_last_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='values',
            name='last_income',
        ),
    ]
