# Generated by Django 4.2.4 on 2023-08-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('withdraw', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
