# Generated by Django 4.2.4 on 2023-08-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_user_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='done',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
