# Generated by Django 4.2.4 on 2023-08-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_user_done_remove_user_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
