# Generated by Django 4.2.4 on 2023-08-11 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_user_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='value',
        ),
    ]
